Default: &defaults
  user: whatisdh
  password: whatisdh
  host: localhost
  port: 5432
  database: whatisdh
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: whatisdh_test
  <<: *defaults

Staging:
  database: whatisdh_staging
  poolsize: 100
  <<: *defaults

Production:
  database: whatisdh_production
  poolsize: 100
  <<: *defaults
