Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  title: What is DH?
  copyright: Copyright © 2012

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://whatisdh.herokuapp.com"
  analytics: UA-33512822-1
  <<: *defaults
